Jlc/match attributes of relationships
nelc/frontend-essentials pull request #26
Opened 2023-07-10 21:20 UTC by johanv26

# Description
This configure the read of relationships for the api for each item.
For example now, username is a field that belongs to author and not
to the item of feedback in the api.
## After
Component of card continue working with username
![Peek 2023-07-10 16-19](https://github.com/nelc/frontend-essentials/assets/51926076/1891b71b-c068-48c7-9b5c-351040bdfa19)

2023-07-10 21:36 UTC, andrey-canon requested changes
Tests

2023-07-10 21:36 UTC, andrey-canon commented on src/components/Feedback/FeedbackCarousel.tsx
> +interface JsonApiItem {
what is the purpose of this, since you are no reusing this ?

2023-07-10 21:41 UTC, johanv26 commented on src/components/Feedback/FeedbackCarousel.tsx
> +interface JsonApiItem {
I started with this approach to include course_id, but the course_id would be another approach.
https://github.com/nelc/frontend-essentials/pull/26/commits/e2fcb24da4d44cd759ea68391a32e42300840061

2023-07-10 22:39 UTC, andrey-canon commented on src/components/Feedback/FeedbackCarousel.tsx
> +    [key: string | number]: string | number
a key could be a number ? which is the case ?
I think you want to cover  multiples cases but it's still very specific,I mean you are not covering when the value is a boolean so do you need that it's not enough `attributes: object` ?

2023-07-11 17:05 UTC, andrey-canon commented on src/components/Feedback/FeedbackCarousel.tsx
> +    [key: string | number]: string | number
I think that's ok but I'm still wondering if `attributes: object` is not the same

2023-07-11 19:52 UTC, johanv26 commented on src/components/Feedback/FeedbackCarousel.tsx
> +    [key: string | number]: string | number
[4bbd864](https://github.com/nelc/frontend-essentials/pull/26/commits/4bbd86464d122dfbf5e09898867d918b874a67a5)

2023-07-11 20:28 UTC, andrey-canon commented on src/components/Feedback/FeedbackCarousel.tsx
> +    [key: string | number]: string | number
That means that is the same  ?

2023-07-11 20:37 UTC, johanv26 commented on src/components/Feedback/FeedbackCarousel.tsx
> +    [key: string | number]: string | number
Not the same actual object forced to not be a primitive.
So you cant use attributes: true, or attributes: 4, or attributes: "hi"
Also, there is an Object with `O` but this one allow anyone seems
https://stackoverflow.com/questions/49464634/difference-between-object-and-object-in-typescript
https://www.typescripttutorial.net/typescript-tutorial/typescript-object-type/

2023-07-11 20:42 UTC, andrey-canon approved these changes

2023-07-11 20:48 UTC, merged